name: Java Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          ./mvnw install -DskipTests

      - name: Run Checkstyle
        run: ./mvnw checkstyle:check
