name: Super-Linter

on: push

jobs: 
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v2

      - name: Run Supper-Linter
        uses: github/superlinter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}


        
