name: Superlinter

on:
  push:
    branches:
      - main

jobs:
  superlint:
    name: Lint codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Superlinter
        uses: github/super-linter@v4
